name: 'Repository Issue Assigner'
description: 'Github Action to notify newly created issues to code owner'
author: 'kbrashears5'
branding:
  icon: 'upload-cloud'
  color: 'purple'
inputs:
  TOKEN:
    description: 'Base 64 encoded {username}:{token} where token is Personal Access Token with repo scope'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.TOKEN }}