#!/bin/bash

STATUS=0

# remember last error code
trap 'STATUS=$?' ERR

# problem matcher must exist in workspace
cp /error-matcher.json $HOME/issue-assigner-error-matcher.json
echo "::add-matcher::$HOME/issue-assigner-error-matcher.json"

echo "Repository: [$GITHUB_REPOSITORY]"

GITHUB_TOKEN="$INPUT_TOKEN"

echo " "

# determine repo info
REPO_INFO=($(echo $GITHUB_REPOSITORY | tr "/" "\n"))
USER_NAME=${REPO_INFO[0]}
echo "Username: [$USER_NAME]"
REPO_NAME=${REPO_INFO[1]}
echo "Repository name: [$REPO_NAME]"

echo " "

# get latest issue
echo "Getting latest issue on [${REPO_NAME}]"
ISSUES=$(curl -X GET -H "Accept: application/vnd.github.v3+json" --silent "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/issues?sort=updated&direction=desc&state=open&per_page=1" | jq '.[].number')
readarray -t ISSUE_NUMBERS <<< "$ISSUES"
NUMBER="${ISSUE_NUMBERS[0]}"
echo "Issue Number: [${NUMBER}]"

echo " "

echo "Creating automated comment"
MESSAGE="#### AUTOMATICALLY GENERATED by kbrashears5/github-action-issue-notifier

Mentioning @${USER_NAME} to notify them. This will be looked at soon!"

jq -n --arg body "$MESSAGE" \
'{
    body:$body
}' \
| curl -d @- \
    -X POST \
    -H "Accept: application/vnd.github.v3+json" \
    -H "Content-Type: application/json" \
    -u ${GITHUB_TOKEN} \
    --silent \
    ${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/issues/${NUMBER}/comments

# assign issue
# turn repo username into array
readarray -t ASSIGNEES <<< "$USER_NAME"
ASSIGNEES_JSON=`printf '%s\n' "${ASSIGNEES[@]}" | jq -R . | jq -s .`

echo "Assigning issue to [${USER_NAME}]"
jq -n --argjson assignees "$ASSIGNEES_JSON" '{assignees:$assignees}'

# "try/catch" to figure out if token has admin or collaborator permissions to repo
jq -n --argjson assignees "$ASSIGNEES_JSON" \
'{
    assignees:$assignees
}' \
| curl -d @- \
    -X POST \
    -H "Accept: application/vnd.github.v3+json" \
    -H "Content-Type: application/json" \
    -u ${GITHUB_TOKEN} \
    --silent \
    ${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/issues/${NUMBER}/assignees \
|| echo "Token does not have admin permissions to repo. Unable to assign"

exit $STATUS